# Generated by Django 5.1.4 on 2024-12-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_organizer",
            field=models.BooleanField(default=False),
        ),
    ]
