# Generated by Django 5.1.4 on 2024-12-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="trip",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="trip.trip",
            ),
        ),
    ]
