# Generated by Django 5.1.4 on 2024-12-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0004_alter_cart_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="persons",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
