# Generated by Django 5.1.4 on 2024-12-21 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0005_alter_cart_persons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cart",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trip.trip"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
