# Generated by Django 5.1.4 on 2024-12-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0006_alter_cart_total_price_alter_cart_trip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="persons",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="trip",
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persons", models.PositiveIntegerField(default=1)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trip.cart",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trip.trip"
                    ),
                ),
            ],
        ),
    ]
